accounts/urls.py
from django.urls import path, include
from . import views
app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register_ulr'),
    path('edit-profile/', views.edit_user_profile, name='edit_profile_ulr'),
    path('login/', views.login_view, name='login'),
    path('', include("django.contrib.auth.urls")), # Masalan: 'login/', 'logout/', 'password_change', 'password_reset/' va ..... Bu url standart funksiyalarg olib bradi. Bu funksiyalr Django bilan birga keladi.
]

foodie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include("sandbox.urls")),
    path('recipes/', include("recipes.urls")),
    path('comments/', include("comments.urls")),
    path('accounts/', include("accounts.urls")),
    path('', include("foodie_app.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipes, name='recipes_ulr'),
    path('<int:recipe_id>/', views.recipe_detail, name='recipe_detail_ulr'),
    path('<int:recipe_id>/toggle_favorite/', views.toggle_favorite, name='toggle_favorite_ulr'),
    path('my_favorites', views.my_favorite_recipes, name='my_favorite_recipes_ulr'),

    path('<int:recipe_id>/delete/', views.delete_recipe, name='delete_recipe_ulr'),
    path('<int:recipe_id>/edite/', views.edit_recipe, name='edit_recipe_ulr'),

    path('search/', views.search_results, name='search_results_ulr'),
]

recipes/models.py
from django.contrib.admin import TabularInline
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from foodie_app.models import Category


# Create your models here.



class Recipes(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    ingredients = models.TextField(null=True, blank=True)
    directions = models.TextField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipes')
    favorited_by = models.ManyToManyField(User, related_name='favorite_recipes', blank=True)
    image = models.ImageField(upload_to="recipe_images",null=True, blank=True)



    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipes:recipe_detail_ulr', kwargs={'recipe_id': self.pk})

recipes/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(label='', required=False,
                    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Search recipes...'}))

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect

from comments.forms import CommentForm
from foodie_app.models import Category
from recipes.forms import SearchForm
from recipes.models import Recipes
from foodie_app.forms import RecipeForm

# Create your views here.

def recipes(request):
    recipes = Recipes.objects.all()
    return render(request, 'recipes/recipes.html', {'recipes': recipes})

def recipe_detail(request, recipe_id):
    # recipe = Recipes.objects.get(id=recipe_id)
    recipe = get_object_or_404(Recipes, id=recipe_id)
    comments = recipe.comments.all()

    new_comment = None


    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.recipe = recipe
            new_comment.user = request.user
            new_comment.save()
            return redirect(recipe.get_absolute_url())
    else:
        comment_form = CommentForm()




    return render(request, "recipes/"
                           "recipe.html", {'recipe': recipe, 'comments':comments, 'comment_form': comment_form})



def add_recipe(request, category_id=None):
    category = None
    if category_id:
        # category = Category.objects.get(id=category_id)
        category = get_object_or_404(Category, id=category_id)
        form = RecipeForm(request.POST or None, initial={"category": category})
    else:
        form = RecipeForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        new_recipe = form.save(commit=True)
        return redirect("foodie_app:recipes", category_id=new_recipe.category.id)

    render(request, 'recipes/add_recipe.html', {'form': form, 'category': category})

def search_results(request):
    form = SearchForm(request.GET)   # request.GET ni to'g'ridan-to'g'ri berish
    query = form.data.get("query", "")  # form dan query ni olish
    results = Recipes.objects.filter(name__icontains=query) if query else []
    context = {'results': results, 'query': query}
    return render(request, 'recipes/search_results.html', context)

@login_required
def toggle_favorite(request, recipe_id):
    print(recipe_id)
    recipe = get_object_or_404(Recipes, id=recipe_id)
    if request.user in recipe.favorited_by.all():
        recipe.favorited_by.remove(request.user)
    else:
        recipe.favorited_by.add(request.user)
    return redirect("recipes:recipe_detail_ulr", recipe_id=recipe_id)

@login_required
def my_favorite_recipes(request):

    user = request.user
    favorites = user.favorite_recipes.all()
    return render(request,"recipes/my_favorites.html", {'favorites': favorites})

@login_required
def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipes, id=recipe_id)
    if not request.user == recipe.user and not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == "POST":
        recipe.delete()
        return redirect('foodie_app:recipes-category-ulr', category_id=recipe.category.id)

    return render(request, "recipes/recipe_confirmation_delete.html", {'recipe': recipe})


@login_required
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipes, id=recipe_id)

    if not request.user == recipe.user and not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == "POST":
        form = RecipeForm(data=request.POST, files=request.FILES, instance=recipe)
        if form.is_valid():
            form.save(commit=True)
            return redirect("recipes:recipe_detail_ulr", recipe_id=recipe_id)
    else:
        form = RecipeForm(instance=recipe)
    return render(request, "recipes/edit_recipe.html", {'recipe': recipe, 'form': form})

recipes/templates/recipes/add_recipe.html
{% extends "base.html" %}
{% block page_header %}
     <h3>
        Add Recipe
        {% if category %} to  {{ category.name }}{% endif %}
    </h3>
{% endblock %}


{% block content %}

    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_div }}
            <button class="btn btn-outline-success"  type="submit">Save Recipe1</button>
        </form>
    </div>

{% endblock content %}

recipes/templates/recipes/edit_recipe.html
{% extends "base.html" %}
{% block page_header %}
     <h3>
        Add Edite
        {% if category %} to  {{ category.name }}{% endif %}
    </h3>
{% endblock %}


{% block content %}

    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_div }}
            <button class="btn btn-outline-success"  type="submit">Yes, Edite</button>
            <a href="{% url 'recipes:recipe_detail_ulr' recipe_id=recipe.id %}">Cancel</a>
        </form>
    </div>

{% endblock content %}

recipes/templates/recipes/my_favorites.html
{% extends "base.html" %}

{% block page_header %}
    <h5>My favorite recipes</h5>
{% endblock page_header %}

{% block content %}
    <div>
        {% for recipe in favorites %}
            <div class="card mb-3 mx-auto" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        {% if recipe.image %}
                            <img width="100%" class="image-fluid rounded-start shadow" src="{{ recipe.image.url }}" alt="{{ recipe.name }}">
                        {% else %}
                            <img width="100%" class="image-fluid rounded-start shadow" src="https://placehold.co/800?text=placeholder" alt="recipe">
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.name }}</h5>
                            <p>Description:</p>
                            <p class="card-text">{{ recipe.description }}</p>
                            <p class="card-text"><small class="text-body-secondary">Added: {{ recipe.date_created| date:"d M, Y H:i" }}</small></p>
                            <small><a href="{% url 'recipes:recipe_detail_ulr' recipe.id %}">View recipe detail</a></small>
                        </div>
                    </div>
                </div>
            </div>
            
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/recipe.html
{% extends "base.html" %}

{% block content %}
    <div class="card mb-3 mx-auto">
        <div class="row g-0">
            <div class="col-md-4">
                {% if recipe.image %}
                    <img width="100%" class="image-fluid rounded-start shadow" src="{{ recipe.image.url }}"
                         alt="{{ recipe.name }}">
                {% else %}
                    <img width="100%" class="image-fluid rounded-start shadow"
                         src="https://placehold.co/800?text=placeholder" alt="recipe">
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ recipe.name }}</h5>
                    <p>Description:</p>
                    <p class="card-text">{{ recipe.description }}</p>
                </div>
                <div class="card-body">
                    <p>Ingredients:</p>
                    <p class="card-text">{{ recipe.ingredients }}</p>
                </div>
                <div class="card-body">
                    <p>Directions:</p>
                    <p class="card-text">{{ recipe.directions }}</p>
                </div>
                <div class="d-flex justify-content-between mx-3 mb-3">
                    <div class="d-flex align-items-end me-auto">
                        <small class="text-body-secondary ">Added: {{ recipe.date_created| date:"d M, Y H:i" }}</small>
                    </div>
                    <div class="me-3">
                        <form action="{% url 'recipes:toggle_favorite_ulr' recipe_id=recipe.id %}">
                            {% csrf_token %}
                            {% if recipe in user.favorite_recipes.all %}
                                <button type="submit" class="btn btn-link p-0 m-0"><i class="fas fa-heart"
                                                                                      style="color:red"></i></button>
                            {% else %}
                                <button type="submit" class="btn btn-link p-0 m-0"><i class="far fa-heart"></i></button>
                            {% endif %}
                        </form>

                    </div>
                    <div class="me-3">
                        <a href="{% url 'recipes:delete_recipe_ulr' recipe_id=recipe.id %}">Delete</a>
                    </div>
                    <div>
                        <a href="{% url 'recipes:edit_recipe_ulr' recipe_id=recipe.id %}">Edite</a>
                    </div>


                </div>

            </div>
        </div>
    </div>

    <div class="mt-4">
        <h5>Comments:</h5>
        {% for comment in  comments %}
            <div class="border p-3 mb-3 rounded">
                <div class="d-flex align-items-center mb-2">
                    {% if user.profile.profile_photo %}
                        <img src="{{ user.profile.profile_photo.url }}" alt="Profile"
                             style="width: 40px; height: 40px; border-radius: 50%; margin-right: 5px">
                    {% endif %}
                    <div>
                        <strong>{{ comment.user.username }}</strong>
                        Commented on {{ comment.date_created|date:"F d, Y" }} at {{ comment.date_created|time:"H:i" }}:
                        <br>
                        <p class="fst-italic">"{{ comment.text }}"</p>
                    </div>
                </div>
            </div>
        {% empty %}
            No comment yet.
        {% endfor %}
    </div>
    <!-- Comment Form   -->
    {% if user.is_authenticated %}
        <h5>Leave comment:</h5>
        <form method="post">
            {% csrf_token %}
            {{ comment_form.as_div }}
            <div class="mt-2">
                <button type="submit" class="btn btn-primary">Add Commite</button>
            </div>
        </form>
    {% else %}
        <p><a class="btn btn-success" href="{% url 'accounts:login' %}">Log in</a> to post a comment</p>
    {% endif %}
{% endblock content %}

recipes/templates/recipes/recipe_confirmation_delete.html
{% extends "base.html" %}

{% block content %}

        <div class="container">
            <h2>Are you sure want to delete {{ recipe }}</h2>
            <form method="post" action="{% url 'recipes:delete_recipe_ulr' recipe_id=recipe.id %}">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Yes, delete</button>
                <a href="{% url 'recipes:recipe_detail_ulr' recipe_id=recipe.id %}">Cancel</a>
            </form>
        </div>


{% endblock content %}

recipes/templates/recipes/recipes.html
{% extends "base.html" %}

{% block page_header %}
    <h5>Recipe</h5>
{% endblock page_header %}

{% block content %}
    <div>
        {% for recipe in recipes %}
            <div class="card mb-3 mx-auto" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        {% if recipe.image %}
                            <img width="100%" class="image-fluid rounded-start shadow" src="{{ recipe.image.url }}" alt="{{ recipe.name }}">
                        {% else %}
                            <img width="100%" class="image-fluid rounded-start shadow" src="https://placehold.co/800?text=placeholder" alt="recipe">
                        {% endif %}
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.name }}</h5>
                            <p>Description:</p>
                            <p class="card-text">{{ recipe.description }}</p>
                            <p class="card-text"><small class="text-body-secondary">Added: {{ recipe.date_created| date:"d M, Y H:i" }}</small></p>
                            <small><a href="{% url 'recipes:recipe_detail_ulr' recipe.id %}">View recipe detail</a></small>
                        </div>
                    </div>
                </div>
            </div>












{#            <div class="card mb-3">#}
{#                <div class="card-header">#}
{#                    <h5>{{ recipe.name }}, Added: {{ recipe.date_created| date:"d M, Y H:i" }}</h5>#}
{#                </div>#}
{#                <div class="card-body">#}
{#                    <h5 class="card-title">Description:</h5>#}
{#                    <p class="card-text">{{ recipe.description }}</p>#}
{#                    <div class="row align-items-center">#}
{#                        <div class="col">#}
{#                            <small><a href="{% url 'recipes:recipe_detail_ulr' recipe.id %}" class="btn btn-primary">View#}
{#                                recipe detail</a></small>#}
{#                        </div>#}
{#                        <div class="col-auto">#}
{#                            {% if user.profile.profile_photo %}#}
{#                                <img src="{{ user.profile.profile_photo.url }}" alt="Profile"#}
{#                                     style="width: 40px; height: 40px; border-radius: 50%; margin-right: 5px">#}
{#                            {% endif %}#}
{#                        <small> Created by: {{ recipe.user.username }}</small>#}
{#                        </div>#}
{##}
{#                    </div>#}
{##}
{#                </div>#}
{#            </div>#}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/search_results.html
{% extends "base.html" %}

{% block page_header %}
    <h5>Recipe</h5>
{% endblock page_header %}

{% block content %}
    <div class="container mt-4">
        {% if results %}
            {% for recipe in results %}
                <div class="card mb-3">
                    <div class="card-header">
                        <h5>{{ recipe.name }}, Added: {{ recipe.date_created| date:"d M, Y H:i" }}</h5>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Description:</h5>
                        <p class="card-text">{{ recipe.description }}</p>
                        <div class="row align-items-center">
                            <div class="col">
                                <small><a href="{% url 'recipes:recipe_detail_ulr' recipe.id %}"
                                          class="btn btn-primary">View
                                    recipe detail</a></small>
                            </div>
                            <div class="col-auto">
                                {% if user.profile.profile_photo %}
                                    <img src="{{ user.profile.profile_photo.url }}" alt="Profile"
                                         style="width: 40px; height: 40px; border-radius: 50%; margin-right: 5px">
                                {% endif %}
                                <small> Created by: {{ recipe.user.username }}</small>
                            </div>

                        </div>

                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No recipes found for "{{ query }}"</p>
        {% endif %}


    </div>
{% endblock content %}