foodie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include("sandbox.urls")),
    path('recipes/', include("recipes.urls")),
    path('comments/', include("comments.urls")),
    path('accounts/', include("accounts.urls")),
    path('', include("foodie_app.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodie_app/urls.py
from django.urls import path
from . import views

app_name = 'foodie_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>', views.recipes_category, name='recipes-category-ulr'),
    path('add-category/', views.add_category, name='add-category-ulr'),
    path('add-recipe/', views.add_recipe, name='add-recipe-ulr'),
    path('add-recipe/category/<int:category_id>/', views.add_recipe, name='add-recipe-with-ulr'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipes, name='recipes_ulr'),
    path('<int:recipe_id>/', views.recipe_detail, name='recipe_detail_ulr'),
    path('<int:recipe_id>/toggle_favorite/', views.toggle_favorite, name='toggle_favorite_ulr'),
    path('my_favorites', views.my_favorite_recipes, name='my_favorite_recipes_ulr'),

    path('<int:recipe_id>/delete/', views.delete_recipe, name='delete_recipe_ulr'),
    path('<int:recipe_id>/edite/', views.edit_recipe, name='edit_recipe_ulr'),

    path('search/', views.search_results, name='search_results_ulr'),
]

foodie_app/models.py
from symtable import Class

from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id',)
        verbose_name = "Kategoriyalar1"
        verbose_name_plural = "Kategoriyar2"

    def __str__(self):
        return self.name

recipes/models.py
from django.contrib.admin import TabularInline
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from foodie_app.models import Category


# Create your models here.



class Recipes(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    ingredients = models.TextField(null=True, blank=True)
    directions = models.TextField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='recipes')
    favorited_by = models.ManyToManyField(User, related_name='favorite_recipes', blank=True)
    image = models.ImageField(upload_to="recipe_images",null=True, blank=True)



    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipes:recipe_detail_ulr', kwargs={'recipe_id': self.pk})

foodie_app/forms.py
from django import forms

from foodie_app.models import Category
from recipes.models import Recipes


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }



class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipes
        fields = ['name', 'description', 'ingredients', 'directions', 'category','image']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'ingredients': forms.Textarea(attrs={'class': 'form-control'}),
            'directions': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'image': forms.ClearableFileInput(attrs={'class':'form-control','multiple': False}),

        }

recipes/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(label='', required=False,
                    widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Search recipes...'}))

foodie_app/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import CategoryForm, RecipeForm
from .models import Category
from recipes.models import Recipes
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    categories = Category.objects.all()
    return render(request, 'foodie_app/index.html', {'categories': categories})


def recipes_category(request, category_id):
    recipes = Recipes.objects.filter(category_id=category_id)
    category = Category.objects.get(id=category_id)
    return render(request, 'foodie_app/recipes.html', {'recipes': recipes, 'category': category})


@login_required
def add_category(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("foodie_app:index")
        else:
            return render(request, 'foodie_app/add_category.html', {'form': form})
    else:
        form = CategoryForm()
        return render(request, 'foodie_app/add_category.html', {'form': form})


# def add_recipe(request):
#     if request.method == "POST":
#         form = RecipeForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("recipes:index")
#     else:
#         form = RecipeForm()
#     return render(request, "foodie_app/add_recipe.html", {'form': form})

@login_required
def add_recipe(request, category_id=None):
    category = None
    if category_id:
        category = get_object_or_404(Category, id=category_id)
        form = RecipeForm(request.POST or None, files=request.FILES, initial={"category": category})
    else:
        form = RecipeForm(request.POST or None, files=request.FILES)
    if request.method == "POST" and form.is_valid():
        new_recipe = form.save(commit=False)
        new_recipe.user = request.user
        new_recipe.save()
        return redirect("recipes:recipes_ulr")

    return render(request, "foodie_app/add_recipe.html", {'form': form})

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect

from comments.forms import CommentForm
from foodie_app.models import Category
from recipes.forms import SearchForm
from recipes.models import Recipes
from foodie_app.forms import RecipeForm

# Create your views here.

def recipes(request):
    recipes = Recipes.objects.all()
    return render(request, 'recipes/recipes.html', {'recipes': recipes})

def recipe_detail(request, recipe_id):
    # recipe = Recipes.objects.get(id=recipe_id)
    recipe = get_object_or_404(Recipes, id=recipe_id)
    comments = recipe.comments.all()

    new_comment = None


    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.recipe = recipe
            new_comment.user = request.user
            new_comment.save()
            return redirect(recipe.get_absolute_url())
    else:
        comment_form = CommentForm()




    return render(request, "recipes/"
                           "recipe.html", {'recipe': recipe, 'comments':comments, 'comment_form': comment_form})



def add_recipe(request, category_id=None):
    category = None
    if category_id:
        # category = Category.objects.get(id=category_id)
        category = get_object_or_404(Category, id=category_id)
        form = RecipeForm(request.POST or None, initial={"category": category})
    else:
        form = RecipeForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        new_recipe = form.save(commit=True)
        return redirect("foodie_app:recipes", category_id=new_recipe.category.id)

    render(request, 'recipes/add_recipe.html', {'form': form, 'category': category})

def search_results(request):
    form = SearchForm(request.GET)   # request.GET ni to'g'ridan-to'g'ri berish
    query = form.data.get("query", "")  # form dan query ni olish
    results = Recipes.objects.filter(name__icontains=query) if query else []
    context = {'results': results, 'query': query}
    return render(request, 'recipes/search_results.html', context)

@login_required
def toggle_favorite(request, recipe_id):
    print(recipe_id)
    recipe = get_object_or_404(Recipes, id=recipe_id)
    if request.user in recipe.favorited_by.all():
        recipe.favorited_by.remove(request.user)
    else:
        recipe.favorited_by.add(request.user)
    return redirect("recipes:recipe_detail_ulr", recipe_id=recipe_id)

@login_required
def my_favorite_recipes(request):

    user = request.user
    favorites = user.favorite_recipes.all()
    return render(request,"recipes/my_favorites.html", {'favorites': favorites})

@login_required
def delete_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipes, id=recipe_id)
    if not request.user == recipe.user and not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == "POST":
        recipe.delete()
        return redirect('foodie_app:recipes-category-ulr', category_id=recipe.category.id)

    return render(request, "recipes/recipe_confirmation_delete.html", {'recipe': recipe})


@login_required
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipes, id=recipe_id)

    if not request.user == recipe.user and not request.user.is_superuser:
        return HttpResponseForbidden()

    if request.method == "POST":
        form = RecipeForm(data=request.POST, files=request.FILES, instance=recipe)
        if form.is_valid():
            form.save(commit=True)
            return redirect("recipes:recipe_detail_ulr", recipe_id=recipe_id)
    else:
        form = RecipeForm(instance=recipe)
    return render(request, "recipes/edit_recipe.html", {'recipe': recipe, 'form': form})

foodie_app/templates/foodie_app/add_category.html
 {% extends "base.html" %}

 {% block content %}
   <h3>Add Recipe</h3>
     <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_div }}
            <button class="btn btn-outline-success mt-2"  type="submit">Save Category</button>
        </form>
     </div>

 {% endblock content %}

foodie_app/templates/foodie_app/add_recipe.html
 {% extends "base.html" %}

{% block page_header %}
     <h3>Add Recipe</h3>
{% endblock page_header %}

 {% block content %}


        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_div }}
            <button class="btn btn-outline-success mt-2"  type="submit">Save Recipe</button>
        </form>


 {% endblock content %}

foodie_app/templates/foodie_app/index.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="col-md-12">
            <h6 class="display-2">Foodie</h6>
            <p class="led"> Foodie - bu sizning oshxonangizdagi ingredientlar asosida retseptlar qidirish imkonini beruvchi veb-ilova. Bundan tashqari, sevimli retseptingizni saqlashingiz va sotib olishingiz kerak bo'lgan ingredientlar uchun xarid ro'yxatini yaratishingiz mumkin.</p>
        </div>
    </div>
    <div class="container">
        <h6 class="display-4"> Ommabop retsept <span class="badge text-bg-secondary">category</span> lari </h6 class="display-4">
    </div>
    <div>
    <div class="row mb-2">
        <div class="col-auto">
            <a class="btn btn-success" href="{% url 'foodie_app:add-category-ulr' %}">Add Category</a>
        </div>

    </div>
    <div class="row">
        {% for category in categories %}
                <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
                <div class="card h-100 text-bg-light mb-3">
                    <div class="crd-body">
                        <a  href="{% url 'foodie_app:recipes-category-ulr' category.id %}">
                            <div class="card-body">{{ category.name }}</div>
                        </a>
                    </div>
            </div>
            </div>
        {% endfor %}
    </div>
    </div>
{% endblock content %}

foodie_app/templates/foodie_app/recipes.html
{% extends "base.html" %}

{% block page_header %}
    <h3>Recipes under <i>{{ category }}</i></h3>
{% endblock page_header %}

{% block content %}
    <div class="row mb-2">
        <div class="col-auto">
            <a class="btn btn-success" href="{% url 'foodie_app:add-recipe-with-ulr' category_id=category.id %}">Add recipe</a>
        </div>
    </div>

    <div>
        {% for recipe in recipes %}

            <div class="card mb-3">
                <div class="card-header">
                    <h5>{{ recipe.name }}, Added: {{ recipe.date_created| date:"d M, Y H:i" }}</h5>
                </div>
                <div class="card-body">


                    <h5 class="card-title">Description:</h5>
                    <p class="card-text"></p>
                    <div class="row align-items-center">
                        <div class="col">
                            <a href="{% url 'recipes:recipe_detail_ulr' recipe.id %}" class="btn btn-primary">View
                                recipe detail</a>
                        </div>
                        <div class="col-auto">
                            <div class="col-auto">
                                {% if user.profile.profile_photo %}
                                    <img src="{{ user.profile.profile_photo.url }}" alt="Profile"
                                         style="width: 40px; height: 40px; border-radius: 50%; margin-right: 5px">
                                {% endif %}
                                <small>{{ user.username }} </small>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}