accounts/urls.py
from django.urls import path, include
from . import views
app_name = 'accounts'
urlpatterns = [
    path('register/', views.register, name='register_ulr'),
    path('edit-profile/', views.edit_user_profile, name='edit_profile_ulr'),
    path('login/', views.login_view, name='login'),
    path('', include("django.contrib.auth.urls")), # Masalan: 'login/', 'logout/', 'password_change', 'password_reset/' va ..... Bu url standart funksiyalarg olib bradi. Bu funksiyalr Django bilan birga keladi.
]

foodie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include("sandbox.urls")),
    path('recipes/', include("recipes.urls")),
    path('comments/', include("comments.urls")),
    path('accounts/', include("accounts.urls")),
    path('', include("foodie_app.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodie_app/urls.py
from django.urls import path
from . import views

app_name = 'foodie_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>', views.recipes_category, name='recipes-category-ulr'),
    path('add-category/', views.add_category, name='add-category-ulr'),
    path('add-recipe/', views.add_recipe, name='add-recipe-ulr'),
    path('add-recipe/category/<int:category_id>/', views.add_recipe, name='add-recipe-with-ulr'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipes, name='recipes_ulr'),
    path('<int:recipe_id>/', views.recipe_detail, name='recipe_detail_ulr'),
    path('<int:recipe_id>/toggle_favorite/', views.toggle_favorite, name='toggle_favorite_ulr'),
    path('my_favorites', views.my_favorite_recipes, name='my_favorite_recipes_ulr'),

    path('<int:recipe_id>/delete/', views.delete_recipe, name='delete_recipe_ulr'),
    path('<int:recipe_id>/edite/', views.edit_recipe, name='edit_recipe_ulr'),

    path('search/', views.search_results, name='search_results_ulr'),
]

templates/base.html
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Foodie</title>
     {% load static %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

     <!-- Our project just needs Font Awesome Free's Solid and Brand files -->

      <!-- Link tags cause URI malformed error -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">








</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'foodie_app:index' %}">Foodie</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav  my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="btn btn-outline-success me-2" href="{% url 'foodie_app:add-recipe-ulr' %}">Add recipe</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success me-2" aria-current="page" href="{% url 'recipes:recipes_ulr' %}">All
                        recipes</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success " aria-current="page" href="{% url 'recipes:my_favorite_recipes_ulr' %}">My Favorite</a>
                </li>
            </ul>


            <!--  Right Side Of Navbar  -->
            <ul class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll">


                <form class="d-flex" role="search" method="get" action="{% url 'recipes:search_results_ulr' %}">
                    {{ search_form.as_div }}
                    <button class="btn btn-outline-success ms-1" type="submit">Search</button>
                </form>


                {% if user.is_authenticated %}
                    <li class="nav-item d-flex align-items-center">
                        {% if user.profile.profile_photo %}
                            <img src="{{ user.profile.profile_photo.url }}" alt="Profile"
                                 style="width: 40px; height: 40px; border-radius: 50%; margin-right: 5px">
                        {% endif %}
                        <span class="nav-text me-2">Hello:</span> <a
                            href="{% url 'accounts:edit_profile_ulr' %}">{{ user.username }}</a>
                    </li>



                    <li class="nav-item">
                        <form class="d-flex" method="post" action="{% url 'accounts:logout' %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-success ms-3" type="submit">Chiqish</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register_ulr' %}">Registration</a>
                    </li>
                    <li class="nav-item">
                        <form class="d-flex" method="post" action="{% url 'accounts:login' %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-success" type="submit">Login</button>
                        </form>
                    </li>

                {% endif %}
            </ul>

        </div>
    </div>
</nav>


<main style="height: 100vh" class="container">


    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}
        {% endblock page_header %}
    </div>
    {% block content %}
    {% endblock content %}

</main>


<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">@ 2029</span>
    </div>
</footer>


</body>
</html>